package kr.or.bit;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BitArtCenter.java
//  @ Date : 2020-03-25
//  @ Author : 
//
//




public interface BitArtCenter {
	public void Ballet();
	public void Concert();
	public void Opera();
}//BitArtCenter End
